function melangerTableau(e){for(let a=e.length-1;a>0;a--){let i=Math.floor(crypto.getRandomValues(new Uint32Array(1))[0]/4294967296*(a+1));[e[a],e[i]]=[e[i],e[a]]}return e}let filmsData=null;const COMBINAISONS_INTERDITES=[["Action","Romance"],["Horreur","Familial"],["Science-Fiction","Histoire"],["Guerre","Com\xe9die"],["Drame","Fantastique"],["Myst\xe8re","Animation"]];function estGenreAutorise(e){return!COMBINAISONS_INTERDITES.some(a=>a.every(a=>e.genre.includes(a)))}async function chargerFilms(){if(!filmsData)try{let e=await fetch(`search/p.json?nocache=${Date.now()}`);if(!e.ok)throw Error(`Erreur HTTP : ${e.status}`);filmsData=await e.json()}catch(a){console.error("Erreur lors du chargement des donn\xe9es des films :",a),filmsData=[]}return filmsData}async function chargerFilmsAvecMelange(){return filmsData||(filmsData=await chargerFilms(),filmsData=melangerTableau(filmsData)),filmsData}async function chargerCategorie(e,a){try{let i=await chargerFilms(),r=melangerTableau(i).filter(a=>a.genre.includes(e)&&estGenreAutorise(a)).slice(0,16),t=document.querySelector(a);t.innerHTML=r.length?r.map(e=>`<div class="single-video">
    <a href="${e.emplacement}" title="${e.nom}">
        <div class="video-img">
            <span class="video-item-content">${e.nom}</span>
            <img src="${e.affiche}" alt="${e.nom}" loading="lazy">
        </div>
    </a>
</div>`).join(""):"<p>Aucun film trouv\xe9.</p>",reinitialiserOwlCarousel(a)}catch(n){console.error(`Erreur lors du chargement des films pour la cat\xe9gorie "${e}" :`,n),document.querySelector(a).innerHTML="<p>Erreur de chargement.</p>"}}function reinitialiserOwlCarousel(e){let a=$(e);a.hasClass("owl-carousel")&&a.owlCarousel("destroy"),a.owlCarousel({loop:!1,margin:10,nav:!0,dots:!0,navText:["<i class='fas fa-angle-left'></i>","<i class='fas fa-angle-right'></i>"],responsive:{0:{items:2},600:{items:4},1e3:{items:7}}})}const CATEGORIES=[{name:"Action",container:".video-carousel-action"},{name:"Drame",container:".video-carousel-drame"},{name:"Horreur",container:".video-carousel-horreur"},{name:"Animation",container:".video-carousel-animation"},{name:"Crime",container:".video-carousel-policier"},{name:"Guerre",container:".video-carousel-guerre"},{name:"Com\xe9die",container:".video-carousel-comedie"},{name:"Histoire",container:".video-carousel-histoire"},{name:"Romance",container:".video-carousel-romance"},{name:"Aventure",container:".video-carousel-aventure"},{name:"Fantastique",container:".video-carousel-fantastique"},{name:"Familial",container:".video-carousel-famille"},{name:"Myst\xe8re",container:".video-carousel-myst\xe8re"},{name:"Thriller",container:".video-carousel-thriller"},{name:"Science-Fiction",container:".video-carousel-science-fiction"}];async function chargerToutesLesCategories(){try{await Promise.all(CATEGORIES.map(({name:e,container:a})=>chargerCategorie(e,a))),console.log("Toutes les cat\xe9gories ont \xe9t\xe9 charg\xe9es avec succ\xe8s.")}catch(e){console.error("Erreur lors du chargement des cat\xe9gories :",e)}}document.addEventListener("DOMContentLoaded",chargerToutesLesCategories),window.addEventListener("popstate",chargerToutesLesCategories);const videoCarousel=document.getElementById("videoCarousel");function reinitialiserOwlCarousel(e){let a=$(e);a.hasClass("owl-carousel")&&a.owlCarousel("destroy"),a.owlCarousel({loop:!1,margin:10,nav:!0,dots:!0,navText:["<i class='fas fa-angle-left'></i>","<i class='fas fa-angle-right'></i>"],responsive:{0:{items:2},600:{items:4},1e3:{items:7}}})}fetch("search/films-en-tendance.json").then(e=>e.json()).then(e=>{e.forEach(e=>{let a=document.createElement("div");a.classList.add("single-video"),a.innerHTML=`
<a href="${e.link}" title="${e.title}">
    <div class="video-img">
        <span class="video-item-content">${e.title}</span>
        <img src="${e.img}" alt="${e.title}" title="${e.title}">
    </div>
</a>
`,videoCarousel.appendChild(a)}),reinitialiserOwlCarousel("#videoCarousel")}).catch(e=>console.error("Erreur lors du chargement des films :",e)),$(document).ready(function(){reinitialiserOwlCarousel("#videoCarousel")}),fetch("search/films-en-tendance.json").then(e=>e.json()).then(e=>{let a=document.querySelector(".view-all-video-area .row");e.forEach(e=>{let i=document.createElement("div");i.classList.add("col-lg-2","col-md-3","col-sm-4","col-xs-12","col-6"),i.innerHTML=`
<div class="single-video">
    <a href="${e.link}" title="${e.title}">
        <div class="video-img">
            <span class="video-item-content">${e.title}</span>
            <img src="${e.img}" alt="${e.title}" title="${e.title}">
        </div>
    </a>
</div>
`,a.appendChild(i)})});